In [1]:
from huggingface_hub import login
import os
from dotenv import load_dotenv
load_dotenv()

hf_token = os.getenv('HUGGINGFACE_TOKEN')
login(hf_token)

/Users/kyrylo/miniforge3/envs/ai/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /Users/kyrylo/.cache/huggingface/token
Login successful


In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "meta-llama/Llama-3.2-1B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(model_name)

In [4]:
from src.dataset import JsonDataset

dataset = JsonDataset(
    file_path="data/json_dataset.jsonl",
    tokenizer=tokenizer,
    max_length=4096,
)

In [7]:
from torch.utils.data import DataLoader
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

In [10]:
for elem in dataloader:
    print(elem["input_ids"][:20])

tensor([[128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        ...,
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009]])
tensor([[128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        ...,
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009]])
tensor([[128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        [128000,   2675,    527,  ..., 128009, 128009, 128009],
        ...,